spring.application.name=ms-andesstay-bff
server.port=8080

spring.config.import=optional:file:.env[.properties]

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

reservas.service.url=${RESERVAS_SERVICE_URL:http://localhost:8082}
usuarios.service.url=${USUARIOS_SERVICE_URL:http://localhost:8081}