spring.application.name=ms-andesstay-bff
server.port=8080

spring.config.import=optional:file:.env[.properties]

# Entra ID configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/e05a6798-9387-460a-beca-a08056fe1ca2/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=ecc9edec-2abe-4cec-9a71-f60b2826c339

# Microservices URLs
reservas.service.url=${RESERVAS_SERVICE_URL:http://localhost:8082}
usuarios.service.url=${USUARIOS_SERVICE_URL:http://localhost:8081}